// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/pet/pet.proto

package store

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PetService service

type PetService interface {
	UpsertPets(ctx context.Context, in *UpsertPetsRequest, opts ...client.CallOption) (*UpsertPetsResponse, error)
}

type petService struct {
	c    client.Client
	name string
}

func NewPetService(name string, c client.Client) PetService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "store"
	}
	return &petService{
		c:    c,
		name: name,
	}
}

func (c *petService) UpsertPets(ctx context.Context, in *UpsertPetsRequest, opts ...client.CallOption) (*UpsertPetsResponse, error) {
	req := c.c.NewRequest(c.name, "PetService.UpsertPets", in)
	out := new(UpsertPetsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PetService service

type PetServiceHandler interface {
	UpsertPets(context.Context, *UpsertPetsRequest, *UpsertPetsResponse) error
}

func RegisterPetServiceHandler(s server.Server, hdlr PetServiceHandler, opts ...server.HandlerOption) error {
	type petService interface {
		UpsertPets(ctx context.Context, in *UpsertPetsRequest, out *UpsertPetsResponse) error
	}
	type PetService struct {
		petService
	}
	h := &petServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PetService{h}, opts...))
}

type petServiceHandler struct {
	PetServiceHandler
}

func (h *petServiceHandler) UpsertPets(ctx context.Context, in *UpsertPetsRequest, out *UpsertPetsResponse) error {
	return h.PetServiceHandler.UpsertPets(ctx, in, out)
}
