version: '3'

services:

  consul:
    image: consul:latest
    command: agent -server -client=0.0.0.0 -dev -node=node0 -bootstrap-expect=1 -data-dir=/tmp/consul 
    ports:
      - 8400:8400
      - 8500:8500
      - 8300:8300
      - 8600:53/udp

  microweb:
    image: microhq/micro
    command: web --address=0.0.0.0:8080
    ports:
      - "80:8080"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_API_NAMESPACE=gomicro.api
    links:
      - consul

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'petstore'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3310:3306'
    expose:
      - '3310'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
volumes:
  mysql-data: